export NACL_DEBUG_ENABLE=1;
export PPAPI_BROWSER_DEBUG=1;
export NACL_PLUGIN_DEBUG=1;
export NACL_PPAPI_PROXY_DEBUG=1;
# 1-255 min/max on NACL_SRPC_DEBUG
NACL_SRPC_DEBUG=255;
# 1-255 min/max on NACLVERBOSITY
NACLVERBOSITY=225;

export NACL_EXE_STDOUT=DEBUG_ONLY:dev://postmessage;
export NACL_EXE_STDERR=DEBUG_ONLY:dev://postmessage;
